server:
   port: 8080
   address: 192.168.100.236
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/springboot
#spring.datasource.username=root
#spring.datasource.password=root
spring:
  mvc:
    static-path-pattern: /static/**
     
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  datasource:
    master:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://192.168.2.27:1433;DatabaseName=AfterSaleDB
#      jdbc-url: jdbc:sqlserver://192.168.100.7:1433;DatabaseName=AfterSaleDB
      username: sa
#      password: 123456
      password: Hwapu2014
    slave1:
       driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
       jdbc-url: jdbc:sqlserver://192.168.2.5:1433;DatabaseName=KYDCustomer
#       jdbc-url: jdbc:sqlserver://192.168.100.7:1433;DatabaseName=KYDCustomer
       username: sa
#       password: 123456
       password: Hwapu2014
    slave2:
       driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
       jdbc-url: jdbc:sqlserver://192.168.2.4:1433;DatabaseName=Hwapu_KydWebSite
#       jdbc-url: jdbc:sqlserver://192.168.100.7:1433;DatabaseName=Hwapu_KydWebSite
       username: sa
#       password: 123456
       password: Hwapu2014
mybatis:
  mapper-locations: classpath:dulk/baseMan/mappers/*.xml
  type-aliases-package:  dulk.baseMan.mapper

logging:
#  path: /Users/jackie/workspace/rome/
  file: kydWeb.log
#server.servlet.context-path=
#spring.mvc.view.prefix=classpath:/templates/
#spring.mvc.view.suffix=.html
#logging.level.dulk.baseMan=DEBUG
#datasource.driver.location=C:/workspace/project/dulk/baseMan/sql/mysql-connector-java-5.1.6.jar